name: CI/CD

on:
  pull_request:
    types: [ready_for_review, assigned]
    branches: [main]
  push:
    branches: [main]

jobs:
  # Run tests and linting on PRs
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript build
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

  # Deploy to production when merged to main
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SERVERLESS_DEPLOY_ROLE_ARN }}
          aws-region: ap-southeast-2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to production
        run: npm run deploy -- --stage prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
